# Generated by Django 2.2.10 on 2020-09-20 07:09

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.CharField(default=apps.api.models.corrector_hora, max_length=200)),
                ('jugada', models.IntegerField()),
                ('tiempo_entre_jugada', models.IntegerField()),
                ('posicion', models.CharField(max_length=200)),
                ('tiempo_total', models.CharField(max_length=200)),
            ],
        ),
    ]
