# Generated by Django 2.2.10 on 2020-09-18 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
    ]
