# Generated by Django 2.2.10 on 2020-09-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='jugada',
            new_name='movimiento',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='tiempo_entre_jugada',
            new_name='tiempo_entre_movimiento',
        ),
        migrations.AddField(
            model_name='jugador',
            name='intento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='n_juego',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='sentimiento',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
