# Generated by Django 2.2.10 on 2020-09-18 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200918_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha',
            field=models.CharField(default=datetime.datetime(2020, 9, 18, 18, 18, 38, 872057, tzinfo=utc), max_length=200),
        ),
    ]
