# Generated by Django 2.2.10 on 2020-09-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='colegio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
