# Generated by Django 2.2.10 on 2020-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200918_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha',
            field=models.CharField(default='2020-09-18 13:34:43', max_length=200),
        ),
    ]
