# Generated by Django 2.2.10 on 2020-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200924_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='estrato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
