# Generated by Django 2.2.10 on 2020-10-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201013_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='codigo',
            field=models.CharField(default='Nada', max_length=200),
            preserve_default=False,
        ),
    ]
