# Generated by Django 2.2.10 on 2020-11-09 14:13

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_children_aros'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoDato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.CharField(default=apps.api.models.corrector_hora, max_length=200)),
                ('n_juego', models.IntegerField()),
                ('intento', models.IntegerField()),
                ('error', models.CharField(default='No', max_length=200)),
                ('n_error', models.IntegerField()),
                ('sentimiento', models.CharField(max_length=200)),
                ('movimiento', models.IntegerField()),
                ('tiempo_entre_movimiento', models.FloatField()),
                ('posicion', models.CharField(max_length=200)),
                ('tiempo_total', models.CharField(max_length=200)),
            ],
        ),
    ]
