# Generated by Django 2.2.10 on 2020-11-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ultimodato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimodato',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
