# Generated by Django 2.2.10 on 2020-11-09 18:43

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201109_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimodato',
            name='error',
            field=models.CharField(blank=True, default='No', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ultimodato',
            name='fecha',
            field=models.CharField(blank=True, default=apps.api.models.corrector_hora, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ultimodato',
            name='intento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimodato',
            name='movimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimodato',
            name='n_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimodato',
            name='n_juego',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimodato',
            name='posicion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ultimodato',
            name='sentimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ultimodato',
            name='tiempo_entre_movimiento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimodato',
            name='tiempo_total',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
