# Generated by Django 2.2.10 on 2021-10-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201109_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
